= `Name`
:toclevels: 3


+++The Name class provides the means to define any number of human readable  names for an object. A name is <b>not</b> to be used for defining inter-object relationships. For inter-object relationships instead use the object identification 'mRID'.+++


[cols="h,3",width=60%]
|===
| Type
| Class


| URI^xref:ROOT::uri_explanation.adoc[?]^
| https://cim.ucaiug.io/ns#Name[`cim:Name`]

|===

'''


[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
Name {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}


NameType {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}


Name -> NameType: name_type


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


== Class hierarchy
* *`Name`*


== Fields


.Reference of fields (attributes and relations)
[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality^xref:ROOT::cardinalities_explained.adoc[?]^ | Type | Description

| <<name_type,`name_type`>>
| `1..*`
| xref::class/NameType.adoc[`NameType`]
//| +++Type of this name.+++
|+++Type of this name.+++
|===

=== Attributes


This class has no attributes.


=== Relations



//[discrete]
[#name_type]
==== `name_type`
+++Type of this name.+++

[cols="h,1",width=60%]
|===
| URI
| https://cim.ucaiug.io/ns#Name.NameType[`cim:Name.NameType`]
| Cardinality
| `1..*`
| Destination class
| xref::class/NameType.adoc[`NameType`]

| Inherited from
| xref::class/Name.adoc[`Name`]

| Glossary mappings^xref:ROOT::what_are_glossary_mappings.adoc[?]^
a|
!===
! Mapping type ! Term

! `closeMatch`
! `nbnl:EAN`
! `exactMatch`
! `schema:gtin13`
!===

|===



