= Meetdata

In this repository the data product _Meetdata_ is maintained.

For all that's maintained here, see: <<Repository structure>>.

== Documentation

The documentation can be found https://netbeheer-nederland.github.io/docs-dev/dp-meetdata/latest[here].

== Repository structure

[source]
----
├── docs <1>
│   ├── antora.yml <2>
│   └── modules
│       ├── ROOT <3>
│       └── information_model <4>
├── examples <5>
├── information_model <6>
│   └── dp_meetdata.schema.linkml.yaml <7>
├── justfile <8>
├── LICENSE <9>
├── poetry.lock <10>
├── pyproject.toml <11>
├── README.adoc <12>
└── schemas <13>
----
<1> The entirety of the documentation source is kept here. This includes manually written text and generated artefacts.
<2> The documentation is defined as an https://docs.antora.org/antora/latest/component-version/[Antora component version]. Configuration is done through this file.
<3> The `ROOT` module contains some of the core documentation pages such as the landing page, index and navigation page, but can (and tends to) also contain manually written content.
<4> This module contains the documentation of the information model/schema. This should be generated using the AsciiDoc generator.
<5> Example data can be found here.
<6> All information models (i.e. technology-agnostic formal descriptions of the data) can be found here.
<7> At least there must be a LinkML schema which follows the naming pattern: `<DATAPRODUCT_NAME>.schema.linkml.yaml`.
<8> In this file all defined tasks for the Just task runner can be found. Very handy for developers.
<9> A license file must always be present to indicate what license is adhered to.
<10> Poetry lock file which describes the exact versions used of all Python dependencies of this project.
<11> Poetry project file where Python dependencies are managed.
<12> You are reading it right now.
<13> Generated (technical) schemas are outputted here.

== For developers

=== Task runner

Make sure to have the https://github.com/casey/just[Just task runner] installed.

Then, for an overview of what tasks it can perform for you, simply run:

[source]
----
$ just
----

==== `.env` file

Many tasks ran by the runner echo the exact command being fed to the shell. This is particularly useful for debugging. You'll notice, though, that many of these commands use environment variables. Those are defined in the `.env` file and can be sourced in your shell for your convenience when you want to copy/paste those commands and (after adjusting them) run them yourself.

CAUTION: If you change or add environment variables, please adhere to the convention of prefixing their names such that it's clear for what project they are defined. This also avoids unintentionally applicable values being effective, or unfortunate name collisions.
